name: Automatización de Pedidos - CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Instalar Chrome en Windows
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
        install-chromedriver: false

    - name: Exportar variables de entorno
      run: |
        echo "CI=true" >> $env:GITHUB_ENV
        echo "AMBIENTE_ACTIVO=URL_CORE" >> $env:GITHUB_ENV
        echo "ENVIRONMENT=CORE" >> $env:GITHUB_ENV
        echo "USERNAME=55285" >> $env:GITHUB_ENV
        echo "PASSWORD=s4ds" >> $env:GITHUB_ENV
      shell: powershell

    - name: Crear carpeta reports
      run: |
        if (!(Test-Path "reports")) {
            New-Item -ItemType Directory -Path "reports"
        } else {
            Write-Host "La carpeta 'reports' ya existe. Continuando..."
        }
      shell: powershell

    - name: Ejecutar pruebas Maven (headless, Selenium Manager)
      run: mvn clean test -Dheadless=true
      shell: powershell

    - name: Listar archivos en reports
      run: |
        Write-Host "Archivos en reports:"
        Get-ChildItem -Recurse reports
      shell: powershell

    - name: Subir reportes personalizados
      uses: actions/upload-artifact@v4
      with:
        name: Reportes-Personalizados
        path: reports/
        if-no-files-found: warn
