name: Automatización de Pedidos - CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Instalar Chrome + ChromeDriver
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
        install-chromedriver: true

    - name: Exportar variables de entorno
      run: |
	    echo "CI=true" >> $GITHUB_ENV
        echo "AMBIENTE_ACTIVO=URL_CORE" >> $GITHUB_ENV
        echo "ENVIRONMENT=CORE" >> $GITHUB_ENV
        echo "USERNAME=55285" >> $GITHUB_ENV
        echo "PASSWORD=s4ds" >> $GITHUB_ENV

    - name: Crear carpeta reports
      run: mkdir -p reports

    - name: Ejecutar pruebas Maven (headless)
      run: mvn clean test -Dheadless=true

    - name: Listar reportes personalizados
      run: |
        echo "Archivos en reports:"
        ls -R reports || echo "No se encontraron reportes"

    - name: Subir reportes personalizados
      uses: actions/upload-artifact@v4
      with:
        name: Reportes-Personalizados
        path: reports/
        if-no-files-found: warn
